version: '3.8'
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - node.name=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: >
      elasticsearch
      -E xpack.security.enabled=false
  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - elasticsearch

volumes:
  mongodata:
  esdata: