version: '3'
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - elasticsearch
volumes:
  mongodb_data:
  elasticsearch_data: